services:
  backend:
    build:
      context: .
      dockerfile: deploy/backend.Dockerfile
    image: parserlr1-backend:dev

  frontend:
    build:
      context: .
      dockerfile: deploy/frontend.Dockerfile
      args:
        VITE_API_BASE: /api   # Nginx proxyea /api -> backend:8000
    image: parserlr1-frontend:dev