name: Build & Deploy (EC2 + GHCR)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Deriva nombres de imagen en minúsculas
      - name: Derive image name (backend)
        run: |
          owner="${GITHUB_REPOSITORY%/*}"
          repo="${GITHUB_REPOSITORY#*/}"
          echo "BACK_IMG=ghcr.io/${owner,,}/${repo,,}-backend" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/backend.Dockerfile
          push: true
          tags: |
            ${{ env.BACK_IMG }}:latest
            ${{ env.BACK_IMG }}:${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Derive image name (frontend)
        run: |
          owner="${GITHUB_REPOSITORY%/*}"
          repo="${GITHUB_REPOSITORY#*/}"
          echo "FRONT_IMG=ghcr.io/${owner,,}/${repo,,}-frontend" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push frontend (nginx)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/frontend.Dockerfile
          push: true
          build-args: |
            VITE_API_BASE=/api
          tags: |
            ${{ env.FRONT_IMG }}:latest
            ${{ env.FRONT_IMG }}:${{ github.sha }}

  deploy-ec2:
    runs-on: ubuntu-latest
    needs: [ build-backend, build-frontend ]
    steps:
      - name: Derive image names
        run: |
          owner="${GITHUB_REPOSITORY%/*}"
          repo="${GITHUB_REPOSITORY#*/}"
          echo "BACK_IMG=ghcr.io/${owner,,}/${repo,,}-backend"  >> $GITHUB_ENV
          echo "FRONT_IMG=ghcr.io/${owner,,}/${repo,,}-frontend" >> $GITHUB_ENV

      - name: Deploy via SSH (Compose pull+up)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -Eeuo pipefail

            REPO_URL="https://github.com/${{ github.repository }}.git"  # si es PRIVADO, ver nota abajo
            TARGET_DIR="${{ secrets.EC2_PATH }}"

            mkdir -p "$TARGET_DIR"
            cd "$TARGET_DIR"

            if [ -d .git ]; then
              git fetch --all || true
              git reset --hard origin/main || true
            else
              git clone --depth 1 "$REPO_URL" .   # <-- deja el repo si no existe
            fi

            # Asegurar carpeta deploy/
            mkdir -p deploy

            # Login GHCR
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

            # Escribir imágenes exactas por SHA (sin espacios)
            printf "BACKEND_IMAGE=%s:%s\nFRONTEND_IMAGE=%s:%s\n" \
              "ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${GITHUB_REPOSITORY#*/,,}-backend" "${GITHUB_SHA}" \
              "ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${GITHUB_REPOSITORY#*/,,}-frontend" "${GITHUB_SHA}" \
              | tee deploy/.env.images > /dev/null

            # (Opcional) usar deploy/.env si existe
            EF=""
            [ -f deploy/.env ] && EF="--env-file deploy/.env"

            # Ejecutar compose apuntando explícitamente al archivo (por si acaso)
            COMPOSE_FILE="docker-compose.yml"
            [ -f "$COMPOSE_FILE" ] || COMPOSE_FILE="docker-compose.yaml"
            [ -f "$COMPOSE_FILE" ] || COMPOSE_FILE="compose.yml"
            [ -f "$COMPOSE_FILE" ] || COMPOSE_FILE="compose.yaml"

            if [ ! -f "$COMPOSE_FILE" ]; then
              echo "❌ No se encontró archivo compose en $TARGET_DIR"
              ls -la
              exit 14
            fi

            docker compose -f "$COMPOSE_FILE" $EF --env-file deploy/.env.images pull
            docker compose -f "$COMPOSE_FILE" $EF --env-file deploy/.env.images up -d --remove-orphans

            docker logout ghcr.io || true
            docker system prune -f
