name: Build & Deploy (EC2 + GHCR)

on:
  push:
    branches: [ "main", "andres" ]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build & deploy"
        required: false
        default: ""

permissions:
  contents: read
  packages: write

env:
  TARGET_BRANCH: ${{ github.event.inputs.branch || github.ref_name }}

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { ref: ${{ env.TARGET_BRANCH }} }

      - name: Derive image + HEAD_SHA
        run: |
          owner="${GITHUB_REPOSITORY%/*}"
          repo="${GITHUB_REPOSITORY#*/}"
          echo "BACK_IMG=ghcr.io/${owner,,}/${repo,,}-backend" >> $GITHUB_ENV
          echo "HEAD_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "head_sha=$GITHUB_SHA" >> $GITHUB_OUTPUT  # fallback
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/backend.Dockerfile
          push: true
          tags: |
            ${{ env.BACK_IMG }}:latest
            ${{ env.BACK_IMG }}:${{ env.HEAD_SHA }}

    outputs:
      head_sha: ${{ env.HEAD_SHA }}

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { ref: ${{ env.TARGET_BRANCH }} }

      - name: Derive image + HEAD_SHA
        id: derive
        run: |
          owner="${GITHUB_REPOSITORY%/*}"
          repo="${GITHUB_REPOSITORY#*/}"
          echo "FRONT_IMG=ghcr.io/${owner,,}/${repo,,}-frontend" >> $GITHUB_ENV
          echo "HEAD_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "head_sha=${{ env.HEAD_SHA }}" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/frontend.Dockerfile
          push: true
          build-args: |
            VITE_API_BASE=/api
          tags: |
            ${{ env.FRONT_IMG }}:latest
            ${{ env.FRONT_IMG }}:${{ env.HEAD_SHA }}

    outputs:
      head_sha: ${{ steps.derive.outputs.head_sha }}

  deploy-ec2:
    runs-on: ubuntu-latest
    needs: [ build-backend, build-frontend ]
    steps:
      - name: Derive names + SHA from frontend build
        run: |
          owner="${GITHUB_REPOSITORY%/*}"
          repo="${GITHUB_REPOSITORY#*/}"
          echo "BACK_IMG=ghcr.io/${owner,,}/${repo,,}-backend"  >> $GITHUB_ENV
          echo "FRONT_IMG=ghcr.io/${owner,,}/${repo,,}-frontend" >> $GITHUB_ENV
          echo "HEAD_SHA=${{ needs.build-frontend.outputs.head_sha }}" >> $GITHUB_ENV

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -Eeuo pipefail
            TARGET_DIR="${{ secrets.EC2_PATH }}"
            BRANCH="${{ env.TARGET_BRANCH }}"

            if [ -n "${{ secrets.GH_READ_TOKEN }}" ]; then
              REPO_URL="https://x-access-token:${{ secrets.GH_READ_TOKEN }}@github.com/${{ github.repository }}.git"
            else
              REPO_URL="https://github.com/${{ github.repository }}.git"
            fi

            mkdir -p "$TARGET_DIR"
            cd "$TARGET_DIR"

            if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
              git fetch --depth 1 origin "$BRANCH"
              git checkout -B "$BRANCH" "origin/$BRANCH"
            else
              git clone --depth 1 --branch "$BRANCH" "$REPO_URL" .
            fi

            mkdir -p deploy

            FRONT_PORT=80
            if ss -ltn '( sport = :80 )' | grep -q ':80'; then FRONT_PORT=8080; fi
            printf "FRONT_HTTP_PORT=%s\nBACK_HTTP_PORT=8000\n" "$FRONT_PORT" > deploy/.env

            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

            printf "BACKEND_IMAGE=%s:%s\nFRONTEND_IMAGE=%s:%s\n" \
              "${{ env.BACK_IMG }}" "${{ env.HEAD_SHA }}" \
              "${{ env.FRONT_IMG }}" "${{ env.HEAD_SHA }}" \
              > deploy/.env.images

            EF="--env-file deploy/.env"
            CF=""
            for f in docker-compose.yml docker-compose.yaml compose.yml compose.yaml; do [ -f "$f" ] && CF="$f" && break; done
            [ -n "$CF" ] || { echo "❌ No compose file"; exit 14; }

            docker compose -f "$CF" $EF --env-file deploy/.env.images pull
            docker compose -f "$CF" $EF --env-file deploy/.env.images up -d --force-recreate --remove-orphans

            docker logout ghcr.io || true
            docker system prune -f